### ISSUE TITLE
[BUG] Failed to encode packet 'clientbound/minecraft:custom_payload' (scheduledtickvisulizer:tick_data_packet)

### ISSUE THREAD

**Issue by RethinkQAQ** [hotpad100c/scheduledtickvisulizer#1]
# 现象
服务器中产生计划刻后, 玩家因为packet错误无法再加入服务器

# 环境
服务器端为1.21 fabric + carpet, 安装scheduledtickvisulizer 1.2.0
客户端 fabric + carpet, 安装scheduledtickvisulizer 1.2.0

# 复现方法
服务器安装scheduledtickvisulizer,客户端是否安装均不影响.
服务器中制造产生计划刻的事件(也就是服务器向客户端发送packet)时会产生此问题,之后玩家无法加入服务器

# log
```
12:02:15] [Netty Server IO #6/ERROR]: Error sending packet clientbound/minecraft:custom_payload
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (scheduledtickvisulizer:tick_data_packet)
	at knot/net.minecraft.client.render.entity.IronGolemEntityRenderer6.handler$zek000$fabric-networking-api-v1$encode(PacketCodecDispatcher.java:547) ~[server-intermediary.jar:?]
	at knot/net.minecraft.client.render.entity.IronGolemEntityRenderer6.encode(PacketCodecDispatcher.java:55) ~[server-intermediary.jar:?]
	at knot/net.minecraft.client.render.entity.IronGolemEntityRenderer6.encode(PacketCodecDispatcher.java:14) ~[server-intermediary.jar:?]
	at knot/net.minecraft.util.shape.SimplePairList5.encode(EncoderHandler.java:26) ~[server-intermediary.jar:?]
	at knot/net.minecraft.util.shape.SimplePairList5.encode(EncoderHandler.java:12) ~[server-intermediary.jar:?]
	at knot/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/net.minecraft.network.ClientConnection$2.write(ClientConnection.java:530) ~[server-intermediary.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/net.minecraft.network.ClientConnection.sendInternal(ClientConnection.java:350) ~[server-intermediary.jar:?]
	at knot/net.minecraft.network.ClientConnection.method_52917(ClientConnection.java:345) ~[server-intermediary.jar:?]
	at knot/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at knot/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at knot/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at knot/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
	at knot/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at knot/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassCastException: class mypals.ml.ScheduledTickDataPayload cannot be cast to class net.minecraft.client.render.debug.BlockOutlineDebugRenderer1 (mypals.ml.ScheduledTickDataPayload and net.minecraft.client.render.debug.BlockOutlineDebugRenderer1 are in unnamed module of loader 'knot' @5cb9f472)
	at knot/net.minecraft.client.render.entity.IronGolemEntityRenderer9$6.encode(PacketCodec.java:42) ~[server-intermediary.jar:?]
	at knot/net.minecraft.client.render.debug.BlockOutlineDebugRenderer0$1.encode(CustomPayload.java:52) ~[server-intermediary.jar:?]
	at knot/net.minecraft.client.render.debug.BlockOutlineDebugRenderer0$1.encode(CustomPayload.java:57) ~[server-intermediary.jar:?]
	at knot/net.minecraft.client.render.debug.BlockOutlineDebugRenderer0$1.encode(CustomPayload.java:39) ~[server-intermediary.jar:?]
	at knot/net.minecraft.client.render.entity.IronGolemEntityRenderer9$8.encode(PacketCodec.java:81) ~[server-intermediary.jar:?]
	at knot/net.minecraft.client.render.entity.IronGolemEntityRenderer9$9.encode(PacketCodec.java:97) ~[server-intermediary.jar:?]
	at knot/net.minecraft.client.render.entity.IronGolemEntityRenderer9$9.encode(PacketCodec.java:87) ~[server-intermediary.jar:?]
	at knot/net.minecraft.client.render.entity.IronGolemEntityRenderer6.encode(PacketCodecDispatcher.java:53) ~[server-intermediary.jar:?]
	... 31 more
```

**Comment by hotpad100c** [comment]
ok,并且感谢提供修复XD
